version: "3.9"
services:
  postgres-users:
    image: postgres:16
    container_name: postgres-users
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    env_file:
      - .env
    depends_on:
      - postgres-users
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-users:5432/users_db?schema=public

volumes:
  users_db_data:
