name: reservation-service-ci
on:
  push:
    paths:
      - "apps/reservation-service/**"
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/reservation-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run prisma:generate
      - run: npm test
      - run: npm run build
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/reservation-service
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t reservation-service:ci .
